# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jWUmEmb1C54LNXaeUAc2b0rMAuftHy4H
"""

def get_radius(prompt):
  r = int(input(prompt))
  return r
def get_circle_area(a):
  area=3.14*a*a
  return area
prompt="넓이를 구하고자 하는 원의 반지름은?"
result=get_radius(prompt)
print("반지름이",result,"인 원의 넓이= 3.14*",result,"*",result,"=",end=" ")
area=get_circle_area(result)
print(area)