# -*- coding: utf-8 -*-
"""hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yWAf_o3yEb5jYO7T6ENl8_sVsil5AMw
"""

def get_integer(prompt):
  a=int(input(prompt))
  return a
def exchange(C):
  cost=C
  n500=C//500
  C%=500
  n100=C//100
  C%=100
  n50=C//50
  C%=50
  n10=C//10
  C%=10
  print("500원 동전의 개수:",n500)
  print("100원 동전의 개수:",n100)
  print("50원 동전의 개수:",n50)
  print("10원 동전의 개수:",n10)
C=get_integer("동전으로 교환하고자 하는 금액은?")
exchange(C)