# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VKFpaKndLm7GMqjCLpkFjmlRtLSvAVFH
"""

discount=int(input("할인율은?"))

def price(prompt):
  c=int(input(prompt))
  return c

def get_fixed_price(p):
  g=p/(1-discount*0.01)
  return g

p=price("A 상품의 할인된 가격은?")
a=get_fixed_price(p)

p=price("B 상품의 할인된 가격은?")
b=get_fixed_price(p)

print("A 상품의 정가는",a,"원")
print("B 상품의 정가는",b,"원")